export const vus = 10;
export const duration = '1m'
export const homeurl = 'https://www.mountsinai.org/'
export const searchurl = 'https://www.mountsinai.org/search'
export const finddoctorurl = 'https://www.mountsinai.org/find-a-doctor';
export const latestdoctor = 'https://www.mountsinai.org/find-a-doctor/result?search-term=Primary%20Care&type=specialty'
export const selectdoctor = 'https://doctor.mountsinai.org/schedule-appointment?pid=0000072500001497174922&officeId=0000072440074827831371&epicVisitId=2252&timeslot=2022-11-12T11:00:00';
export const locationurl = 'https://www.mountsinai.org/locations';
export const avaiableurl = 'https://doctor.mountsinai.org/view-availability';
export const doctorprofile = 'https://www.mountsinai.org/profiles';